### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by craziks-creator** [ESWZY/telegram-news-deploy#2]
When add second link it shows error for second link on log 👇
`IndexError: list index out of range`

Note: error is in channel 3, table3: sscadmit , while first link table1: SSC has successfully posted news to telegram. 
You can check code of main.py👇
`https://github.com/craziks-creator/telegram-news-getting-started`
Ty

**Comment by ESWZY** [comment]
Still a problem? Because I just seen new commits was pushed. If you have any further problem, feel free to ask.

**Comment by ESWZY** [comment]
Oh, I see. Because the website you want to follow does not use a link for each item, but use a JavaScript jump function.

Maybe you need to find a new way to select the information of interest.

**Comment by craziks-creator** [comment]
> Oh, I see. Because the website you want to follow does not use a link for each item, but use a JavaScript jump function.
> 
> Maybe you need to find a new way to select the information of interest.

I have changed the selector
`body > #id`
Ty

**Comment by ESWZY** [comment]
Try this. Just insert to your code with other configurations.

```
    def ssc_id_policy(link):
        return hashlib.md5(link.encode("utf-8")).hexdigest()
    ie1.set_id_policy(ssc_id_policy)
```

**Comment by craziks-creator** [comment]
> Try this. Just insert to your code with other configurations.
> 
> ```
>     def ssc_id_policy(link):
>         return hashlib.md5(link.encode("utf-8")).hexdigest()
>     ie1.set_id_policy(ssc_id_policy)
> ```


I have added but Showing same as before: 


    sscadmit:	List not modified! 0 posted. Wait 
    60s to restart!
    uksssc:	List not modified! 0 posted. Wait 
    60s to restart! 
While there are about 20 links so it should  be posted all 20 as:  

    ssc:   	0 succeeded, 10 posted. Wait 60s to 
    restart!

but it is showing 0 posted for others except ssc

**Comment by ESWZY** [comment]
> > Try this. Just insert to your code with other configurations.
> > ```
> >     def ssc_id_policy(link):
> >         return hashlib.md5(link.encode("utf-8")).hexdigest()
> >     ie1.set_id_policy(ssc_id_policy)
> > ```
> 
> I have added but Showing same as before:
> 
> ```
> sscadmit:	List not modified! 0 posted. Wait 
> 60s to restart!
> uksssc:	List not modified! 0 posted. Wait 
> 60s to restart! 
> ```
> 
> While there are about 20 links so it should be posted all 20 as:
> 
> ```
> ssc:   	0 succeeded, 10 posted. Wait 60s to 
> restart!
> ```
> 
> but it is showing 0 posted for others except ssc

I don't know if this is a problem caused by selector. You can have a try by `document.querySelectorAll('div.inner_page > ul > li a')` function.

![image](https://user-images.githubusercontent.com/32200887/150674048-c607cc6d-27d5-4b2d-98d6-b374f38a8356.png)

**Comment by craziks-creator** [comment]
> 

Ty,  I have changed paragraph selector, first list is showing on channel. 
Will try function  if issue comes. 
Ty

**Comment by craziks-creator** [comment]
> > > Try this. Just insert to your code with other configurations.
> > > ```
> > >     def ssc_id_policy(link):
> > >         return hashlib.md5(link.encode("utf-8")).hexdigest()
> > >     ie1.set_id_policy(ssc_id_policy)
> > > ```
> > 
> > 
> > I have added but Showing same as before:
> > ```
> > sscadmit:	List not modified! 0 posted. Wait 
> > 60s to restart!
> > uksssc:	List not modified! 0 posted. Wait 
> > 60s to restart! 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > While there are about 20 links so it should be posted all 20 as:
> > ```
> > ssc:   	0 succeeded, 10 posted. Wait 60s to 
> > restart!
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but it is showing 0 posted for others except ssc
> 
> I don't know if this is a problem caused by selector. You can have a try by `document.querySelectorAll('div.inner_page > ul > li a')` function.
> 
> ![image](https://user-images.githubusercontent.com/32200887/150674048-c607cc6d-27d5-4b2d-98d6-b374f38a8356.png)

Ty
I have changed paragraph selector, first list is showing on channel.
Will try function if issue comes.
Ty

**Comment by craziks-creator** [comment]
Solved

**Comment by craziks-creator** [comment]
Error for https://ssc.nic.in/MarksStatus/MarksStatusIndex

Selector: https://github.com/craziks-creator/telegram-news-getting-started/blob/4caf95baebbeb829d2b4c1717e2d7b69e104f326/main.py#L85

I have tried all for this but same error for selector 
: (
Please have a look

**Comment by ESWZY** [comment]
> Error for https://ssc.nic.in/MarksStatus/MarksStatusIndex
> 
> Selector: https://github.com/craziks-creator/telegram-news-getting-started/blob/4caf95baebbeb829d2b4c1717e2d7b69e104f326/main.py#L85
> 
> I have tried all for this but same error for selector : ( Please have a look

What elements did you want to select?

**Comment by craziks-creator** [comment]
> > Error for https://ssc.nic.in/MarksStatus/MarksStatusIndex
> > Selector: https://github.com/craziks-creator/telegram-news-getting-started/blob/4caf95baebbeb829d2b4c1717e2d7b69e104f326/main.py#L85
> > I have tried all for this but same error for selector : ( Please have a look
> 
> What elements did you want to select?

All child of select#ddlExam.
I Mean all option elements to check if there any new option added

**Comment by ESWZY** [comment]
> 

Like this?

```python
# Select elements by CSS-based selector
ie1.set_list_selector('select#ddlExam > option') #id_ul_li
ie1.set_outer_title_selector('option')  #id
ie1.set_outer_link_selector('option')
ie1.set_time_selector('span')
ie1.set_id_policy(ssc_id_policy)
ie1.set_source_selector('span.sourceTemplate')
ie1.max_post_length = 2000
```

**Comment by craziks-creator** [comment]
> > 
> 
> Like this?
> 
> ```python
> # Select elements by CSS-based selector
> ie1.set_list_selector('select#ddlExam > option') #id_ul_li
> ie1.set_outer_title_selector('option')  #id
> ie1.set_outer_link_selector('option')
> ie1.set_time_selector('span')
> ie1.set_id_policy(ssc_id_policy)
> ie1.set_source_selector('span.sourceTemplate')
> ie1.max_post_length = 2000
> ```

Yes, 
I  have tried it previously

**Comment by ESWZY** [comment]
> > > 
> > 
> > 
> > Like this?
> > ```python
> > # Select elements by CSS-based selector
> > ie1.set_list_selector('select#ddlExam > option') #id_ul_li
> > ie1.set_outer_title_selector('option')  #id
> > ie1.set_outer_link_selector('option')
> > ie1.set_time_selector('span')
> > ie1.set_id_policy(ssc_id_policy)
> > ie1.set_source_selector('span.sourceTemplate')
> > ie1.max_post_length = 2000
> > ```
> 
> Yes, I have tried it previously

Did it work?

**Comment by craziks-creator** [comment]
> > > > 
> > > 
> > > 
> > > Like this?
> > > ```python
> > > # Select elements by CSS-based selector
> > > ie1.set_list_selector('select#ddlExam > option') #id_ul_li
> > > ie1.set_outer_title_selector('option')  #id
> > > ie1.set_outer_link_selector('option')
> > > ie1.set_time_selector('span')
> > > ie1.set_id_policy(ssc_id_policy)
> > > ie1.set_source_selector('span.sourceTemplate')
> > > ie1.max_post_length = 2000
> > > ```
> > 
> > 
> > Yes, I have tried it previously
> 
> Did it work?

No, same error
[0m
IndexError: list index out of range

**Comment by ESWZY** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Like this?
> > > > ```python
> > > > # Select elements by CSS-based selector
> > > > ie1.set_list_selector('select#ddlExam > option') #id_ul_li
> > > > ie1.set_outer_title_selector('option')  #id
> > > > ie1.set_outer_link_selector('option')
> > > > ie1.set_time_selector('span')
> > > > ie1.set_id_policy(ssc_id_policy)
> > > > ie1.set_source_selector('span.sourceTemplate')
> > > > ie1.max_post_length = 2000
> > > > ```
> > > 
> > > 
> > > Yes, I have tried it previously
> > 
> > 
> > Did it work?
> 
> No, same error �[0m IndexError: list index out of range

Hmmmm... Could you provide a screenshot of this exception?

**Comment by craziks-creator** [comment]
> 

Of which?  Screenshot of error?

**Comment by craziks-creator** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > Like this?
> > > > > ```python
> > > > > # Select elements by CSS-based selector
> > > > > ie1.set_list_selector('select#ddlExam > option') #id_ul_li
> > > > > ie1.set_outer_title_selector('option')  #id
> > > > > ie1.set_outer_link_selector('option')
> > > > > ie1.set_time_selector('span')
> > > > > ie1.set_id_policy(ssc_id_policy)
> > > > > ie1.set_source_selector('span.sourceTemplate')
> > > > > ie1.max_post_length = 2000
> > > > > ```
> > > > 
> > > > 
> > > > Yes, I have tried it previously
> > > 
> > > 
> > > Did it work?
> > 
> > 
> > No, same error �[0m IndexError: list index out of range
> 
> Hmmmm... Could you provide a screenshot of this exception?

Of which? Screenshot of error?

**Comment by ESWZY** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > Like this?
> > > > > > ```python
> > > > > > # Select elements by CSS-based selector
> > > > > > ie1.set_list_selector('select#ddlExam > option') #id_ul_li
> > > > > > ie1.set_outer_title_selector('option')  #id
> > > > > > ie1.set_outer_link_selector('option')
> > > > > > ie1.set_time_selector('span')
> > > > > > ie1.set_id_policy(ssc_id_policy)
> > > > > > ie1.set_source_selector('span.sourceTemplate')
> > > > > > ie1.max_post_length = 2000
> > > > > > ```
> > > > > 
> > > > > 
> > > > > Yes, I have tried it previously
> > > > 
> > > > 
> > > > Did it work?
> > > 
> > > 
> > > No, same error �[0m IndexError: list index out of range
> > 
> > 
> > Hmmmm... Could you provide a screenshot of this exception?
> 
> Of which? Screenshot of error?

Yes. Or the entire error log.

**Comment by craziks-creator** [comment]
> > > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > Like this?
> > > > > > > ```python
> > > > > > > # Select elements by CSS-based selector
> > > > > > > ie1.set_list_selector('select#ddlExam > option') #id_ul_li
> > > > > > > ie1.set_outer_title_selector('option')  #id
> > > > > > > ie1.set_outer_link_selector('option')
> > > > > > > ie1.set_time_selector('span')
> > > > > > > ie1.set_id_policy(ssc_id_policy)
> > > > > > > ie1.set_source_selector('span.sourceTemplate')
> > > > > > > ie1.max_post_length = 2000
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > Yes, I have tried it previously
> > > > > 
> > > > > 
> > > > > Did it work?
> > > > 
> > > > 
> > > > No, same error �[0m IndexError: list index out of range
> > > 
> > > 
> > > Hmmmm... Could you provide a screenshot of this exception?
> > 
> > 
> > Of which? Screenshot of error?
> 
> Yes. Or the entire error log.

Here's screenshot for error log
![IMG_20220129_222206](https://user-images.githubusercontent.com/67502395/151669691-8766b1eb-3ac2-46f4-9c5f-644fdf348afc.jpg)

**Comment by craziks-creator** [comment]
> > > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > Like this?
> > > > > > > ```python
> > > > > > > # Select elements by CSS-based selector
> > > > > > > ie1.set_list_selector('select#ddlExam > option') #id_ul_li
> > > > > > > ie1.set_outer_title_selector('option')  #id
> > > > > > > ie1.set_outer_link_selector('option')
> > > > > > > ie1.set_time_selector('span')
> > > > > > > ie1.set_id_policy(ssc_id_policy)
> > > > > > > ie1.set_source_selector('span.sourceTemplate')
> > > > > > > ie1.max_post_length = 2000
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > Yes, I have tried it previously
> > > > > 
> > > > > 
> > > > > Did it work?
> > > > 
> > > > 
> > > > No, same error �[0m IndexError: list index out of range
> > > 
> > > 
> > > Hmmmm... Could you provide a screenshot of this exception?
> > 
> > 
> > Of which? Screenshot of error?
> 
> Yes. Or the entire error log.

Here's full error log
![Screenshot_2022-01-29-22-25-32-913_com android chrome](https://user-images.githubusercontent.com/67502395/151669838-8344124e-f338-4977-8410-72de6fc073f3.jpg)

Last line is: 
app[worker.1]: IndexError: list index out of range
2022-01-29T16:48:21.406015+00:00 app[worker.1]: [0m

**Comment by craziks-creator** [comment]
> > > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > Like this?
> > > > > > > ```python
> > > > > > > # Select elements by CSS-based selector
> > > > > > > ie1.set_list_selector('select#ddlExam > option') #id_ul_li
> > > > > > > ie1.set_outer_title_selector('option')  #id
> > > > > > > ie1.set_outer_link_selector('option')
> > > > > > > ie1.set_time_selector('span')
> > > > > > > ie1.set_id_policy(ssc_id_policy)
> > > > > > > ie1.set_source_selector('span.sourceTemplate')
> > > > > > > ie1.max_post_length = 2000
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > Yes, I have tried it previously
> > > > > 
> > > > > 
> > > > > Did it work?
> > > > 
> > > > 
> > > > No, same error �[0m IndexError: list index out of range
> > > 
> > > 
> > > Hmmmm... Could you provide a screenshot of this exception?
> > 
> > 
> > Of which? Screenshot of error?
> 
> Yes. Or the entire error log.

Heroku error log: 
![IMG_20220129_223026](https://user-images.githubusercontent.com/67502395/151669971-26ae3080-3ace-4298-9069-375f8d0a3bb5.jpg)

Last line is: 
app[worker.1]: IndexError: list index out of range
2022-01-29T16:48:21.406015+00:00 app[worker.1]: [0m

**Comment by ESWZY** [comment]
It looks like you haven't changed `set_outer_link_selector`

**Comment by ESWZY** [comment]
And for most time, we use `link` instead of `title` as item id. So, you maybe change 

`            link = get_full_link(link_select[0].get('href'), listURL)`

https://github.com/ESWZY/telegram-news/blob/master/telegram_news/template/common.py#L208

to

`            link = link_select[0].get.get_text().strip()`

And disable the requesting of full text:

https://github.com/ESWZY/telegram-news/blob/master/telegram_news/template/common.py#L1114

to

`message = self._get_full('', item=item)`

**Comment by craziks-creator** [comment]
> And for most time, we use `link` instead of `title` as item id. So, you maybe change
> 
> ` link = get_full_link(link_select[0].get('href'), listURL)`
> 
> https://github.com/ESWZY/telegram-news/blob/master/telegram_news/template/common.py#L208
> 
> to
> 
> ` link = link_select[0].get.get_text().strip()`
> 
> And disable the requesting of full text:
> 
> https://github.com/ESWZY/telegram-news/blob/master/telegram_news/template/common.py#L1114
> 
> to
> 
> `message = self._get_full('', item=item)`


2022-01-30T18:51:10.239432+00:00 app[worker.1]: [31merror in sscscore
2022-01-30T18:51:10.239443+00:00 app[worker.1]: Traceback (most recent call last):
2022-01-30T18:51:10.239444+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram_news/template/common.py", line 1137, in work
2022-01-30T18:51:10.239444+00:00 app[worker.1]:     total, posted = self._action()
2022-01-30T18:51:10.239445+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram_news/template/common.py", line 1083, in _action
2022-01-30T18:51:10.239445+00:00 app[worker.1]:     l, num = self._get_list(list_request_url)
2022-01-30T18:51:10.239446+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram_news/template/common.py", line 788, in _get_list
2022-01-30T18:51:10.239447+00:00 app[worker.1]:     return self._extractor.get_items_policy(text, list_request_url)
2022-01-30T18:51:10.239447+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram_news/template/common.py", line 208, in get_items_policy
2022-01-30T18:51:10.239448+00:00 app[worker.1]:     link = get_full_link(link_select[0].get('href'), listURL)
2022-01-30T18:51:10.239448+00:00 app[worker.1]: IndexError: list index out of range
2022-01-30T18:51:10.239448+00:00 app[worker.1]: [0m
2022-01-30T18:51:17.896628+00:00 app[worker.1]: sscadmit:	List not modified! 1 posted. Wait 60s to restart!
2022-01-30T18:51:21.469717+00:00 app[worker.1]: sscnrstatus:	List not modified! 1 posted. Wait 60s to restart!
2022-01-30T18:51:24.089964+00:00 app[worker.1]: ssc:   	0 succeeded, 10 posted. Wait 60s to restart!
2022-01-30T18:51:38.790369+00:00 app[worker.1]: Nrnews:	List not modified! 10 posted. Wait 60s to restart!

**Comment by craziks-creator** [comment]
> And for most time, we use `link` instead of `title` as item id. So, you maybe change
> 
> ` link = get_full_link(link_select[0].get('href'), listURL)`
> 
> https://github.com/ESWZY/telegram-news/blob/master/telegram_news/template/common.py#L208
> 
> to
> 
> ` link = link_select[0].get.get_text().strip()`
> 
> And disable the requesting of full text:
> 
> https://github.com/ESWZY/telegram-news/blob/master/telegram_news/template/common.py#L1114
> 
> to
> 
> `message = self._get_full('', item=item)`

/telegram_news/template/common.py", line 208, in get_items_policy
2022-01-30T19:08:01.984563+00:00 app[worker.1]:     link = link_select[0].get.get_text().strip()
2022-01-30T19:08:01.984636+00:00 app[worker.1]: AttributeError: 'function' object has no attribute 'get_text'
2022-01-30T19:08:01.984760+00:00 app[worker.1]: [0m
2022-01-30T19:08:01.992515+00:00 app[worker.1]: [31merror in sscscore
2022-01-30T19:08:01.992596+00:00 app[worker.1]: Traceback (most recent call last):
2022-01-30T19:08:01.992621+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram_news/template/common.py", line 1137, in work
2022-01-30T19:08:01.992622+00:00 app[worker.1]:     total, posted = self._action()
2022-01-30T19:08:01.992622+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram_news/template/common.py", line 1083, in _action
2022-01-30T19:08:01.992623+00:00 app[worker.1]:     l, num = self._get_list(list_request_url)
2022-01-30T19:08:01.992624+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram_news/template/common.py", line 788, in _get_list
2022-01-30T19:08:01.992625+00:00 app[worker.1]:     return self._extractor.get_items_policy(text, list_request_url)
2022-01-30T19:08:01.992626+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram_news/template/common.py", line 208, in get_items_policy
2022-01-30T19:08:01.992627+00:00 app[worker.1]:     link = link_select[0].get.get_text().strip()
2022-01-30T19:08:01.992645+00:00 app[worker.1]: IndexError: list index out of range
2022-01-30T19:08:01.992659+00:00 app[worker.1]: [0m
2022-01-30T19:08:02.052933+00:00 app[worker.1]: [31merror in ssc

**Comment by ESWZY** [comment]
That is a typo. I mean `link = link_select[0].get_text().strip()`.

And the modification is just for https://ssc.nic.in/MarksStatus/MarksStatusIndex, maybe not suitable for other source.

**Comment by craziks-creator** [comment]
> That is a typo. I mean `link = link_select[0].get_text().strip()`.
> 
> And the modification is just for https://ssc.nic.in/MarksStatus/MarksStatusIndex, maybe not suitable for other source.

Yes, others have link. So I should build another bot for that particular purpose.

**Comment by craziks-creator** [comment]
> That is a typo. I mean `link = link_select[0].get_text().strip()`.
> 
> And the modification is just for https://ssc.nic.in/MarksStatus/MarksStatusIndex, maybe not suitable for other source.

app[worker.1]: [31merror in sscscore
2022-01-29T16:48:21.405854+00:00 app[worker.1]: Traceback (most recent call last):
2022-01-29T16:48:21.405895+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram_news/template/common.py", line 1137, in work
2022-01-29T16:48:21.405895+00:00 app[worker.1]:     total, posted = self._action()
2022-01-29T16:48:21.405925+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram_news/template/common.py", line 1083, in _action
2022-01-29T16:48:21.405925+00:00 app[worker.1]:     l, num = self._get_list(list_request_url)
2022-01-29T16:48:21.405942+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram_news/template/common.py", line 788, in _get_list
2022-01-29T16:48:21.405943+00:00 app[worker.1]:     return self._extractor.get_items_policy(text, list_request_url)
2022-01-29T16:48:21.405957+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram_news/template/common.py", line 208, in get_items_policy
2022-01-29T16:48:21.405958+00:00 app[worker.1]:     link = get_full_link(link_select[0].get('href'), listURL)
2022-01-29T16:48:21.405983+00:00 app[worker.1]: IndexError: list index out of range

**Comment by craziks-creator** [comment]
> That is a typo. I mean `link = link_select[0].get_text().strip()`.
> 
> And the modification is just for https://ssc.nic.in/MarksStatus/MarksStatusIndex, maybe not suitable for other source.


2022-01-31T07:09:43.242239+00:00 app[worker.1]: [31merror in sscscore
2022-01-31T07:09:43.242314+00:00 app[worker.1]: Traceback (most recent call last):
2022-01-31T07:09:43.242333+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram_news/template/common.py", line 1137, in work
2022-01-31T07:09:43.242334+00:00 app[worker.1]:     total, posted = self._action()
2022-01-31T07:09:43.242336+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram_news/template/common.py", line 1083, in _action
2022-01-31T07:09:43.242336+00:00 app[worker.1]:     l, num = self._get_list(list_request_url)
2022-01-31T07:09:43.242344+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram_news/template/common.py", line 788, in _get_list
2022-01-31T07:09:43.242344+00:00 app[worker.1]:     return self._extractor.get_items_policy(text, list_request_url)
2022-01-31T07:09:43.242346+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram_news/template/common.py", line 208, in get_items_policy
2022-01-31T07:09:43.242346+00:00 app[worker.1]:     link = link_select[0].get_text().strip()
2022-01-31T07:09:43.242360+00:00 app[worker.1]: IndexError: list index out of range
2022-01-31T07:09:43.242369+00:00 app[worker.1]: [0m
2022-01-31T07:09:49.169446+00:00

**Comment by ESWZY** [comment]
> > That is a typo. I mean `link = link_select[0].get_text().strip()`.
> > And the modification is just for https://ssc.nic.in/MarksStatus/MarksStatusIndex, maybe not suitable for other source.
> 
> Yes, others have link. So I should build another bot for that particular purpose.

That's true.
