### ISSUE TITLE
KeyError: 'id'

### ISSUE THREAD

**Issue by craziks-creator** [ESWZY/telegram-news-deploy#5]
2022-02-22T07:19:14.675478+00:00 app[worker.1]: KeyError: 'id'
2022-02-22T07:19:14.675488+00:00 app[worker.1]: [0m
2022-02-22T07:20:02.112442+00:00 app[api]: Scaled to worker@0:Free by user 
2022-02-22T07:20:02.763976+00:00 heroku[worker.1]: State changed from up to down
2022-02-22T07:20:03.585799+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2022-02-22T07:20:03.784181+00:00 heroku[worker.1]: Process exited with status 143
2022-02-22T07:20:12.682603+00:00 app[api]: Scaled to worker@1:Free by user 
2022-02-22T07:20:19.843967+00:00 heroku[worker.1]: Starting process with command `python main.py`
2022-02-22T07:20:20.481688+00:00 heroku[worker.1]: State changed from starting to up
2022-02-22T07:20:22.241409+00:00 app[worker.1]: Set table name "ssc" successfully, table already exists!
2022-02-22T07:20:37.203144+00:00 app[worker.1]: [31merror in ssc
2022-02-22T07:20:37.203893+00:00 app[worker.1]: Traceback (most recent call last):
2022-02-22T07:20:37.203957+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram_news/template/common.py", line 1137, in work
2022-02-22T07:20:37.203958+00:00 app[worker.1]:     total, posted = self._action()
2022-02-22T07:20:37.203990+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram_news/template/common.py", line 1118, in _action
2022-02-22T07:20:37.203990+00:00 app[worker.1]:     res = self._post(message, item['id'])
2022-02-22T07:20:37.204021+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram_news/template/common.py", line 1018, in _post
2022-02-22T07:20:37.204022+00:00 app[worker.1]:     data, method = self._data_format(item, news_id)
2022-02-22T07:20:37.204047+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram_news/template/common.py", line 927, in _data_format
2022-02-22T07:20:37.204047+00:00 app[worker.1]:     data = self._display_policy(item, max_len=self._extractor.max_post_length)
2022-02-22T07:20:37.204063+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram_news/displaypolicy.py", line 131, in best_effort_display_policy
2022-02-22T07:20:37.204065+00:00 app[worker.1]:     return "Too long message!\n" + item['id'], parse_mode, disable_web_page_preview
2022-02-22T07:20:37.204102+00:00 app[worker.1]: KeyError: 'id'
2022-02-22T07:20:37.204141+00:00 app[worker.1]: [0m

**Comment by ESWZY** [comment]
Keep using: `ie1.set_id_policy(ssc_id_policy)`

**Comment by craziks-creator** [comment]
> Keep using: `ie1.set_id_policy(ssc_id_policy)`

Yes, i was using `ie1.set_id_policy(ssc_id_policy)`

**Comment by ESWZY** [comment]
> > Keep using: `ie1.set_id_policy(ssc_id_policy)`
> 
> Yes, i was using `ie1.set_id_policy(ssc_id_policy)`

Could you show me your code?
